/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;

/**
 *
 * @author sharo
 */
public class a_main extends javax.swing.JFrame {

    /**
     * Creates new form a_main
     */
    public a_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        dp = new javax.swing.JDesktopPane();
        ebtn = new javax.swing.JButton();
        dbtn = new javax.swing.JButton();
        ddbtn = new javax.swing.JButton();
        ubtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        dp2 = new javax.swing.JDesktopPane();
        ebtn1 = new javax.swing.JButton();
        dbtn1 = new javax.swing.JButton();
        ddbtn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dp.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel4.add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 680, 420));

        ebtn.setBackground(new java.awt.Color(255, 204, 204));
        ebtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ebtn.setText("Employee ");
        ebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebtnActionPerformed(evt);
            }
        });
        jPanel4.add(ebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        dbtn.setBackground(new java.awt.Color(102, 255, 255));
        dbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        dbtn.setText("Department ");
        dbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbtnActionPerformed(evt);
            }
        });
        jPanel4.add(dbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        ddbtn.setBackground(new java.awt.Color(255, 204, 102));
        ddbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ddbtn.setText("Designation");
        ddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddbtnActionPerformed(evt);
            }
        });
        jPanel4.add(ddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        ubtn.setBackground(new java.awt.Color(204, 51, 255));
        ubtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ubtn.setText("UserAccount");
        ubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubtnActionPerformed(evt);
            }
        });
        jPanel4.add(ubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dp2.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout dp2Layout = new javax.swing.GroupLayout(dp2);
        dp2.setLayout(dp2Layout);
        dp2Layout.setHorizontalGroup(
            dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        dp2Layout.setVerticalGroup(
            dp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel5.add(dp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 680, 420));

        ebtn1.setBackground(new java.awt.Color(255, 204, 204));
        ebtn1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ebtn1.setText("Employee ");
        ebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebtn1ActionPerformed(evt);
            }
        });
        jPanel5.add(ebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        dbtn1.setBackground(new java.awt.Color(102, 255, 255));
        dbtn1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        dbtn1.setText("Department ");
        dbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbtn1ActionPerformed(evt);
            }
        });
        jPanel5.add(dbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        ddbtn1.setBackground(new java.awt.Color(255, 204, 102));
        ddbtn1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ddbtn1.setText("Designation");
        ddbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddbtn1ActionPerformed(evt);
            }
        });
        jPanel5.add(ddbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharo\\OneDrive\\Desktop\\Semester 2 assingment\\java\\OopAssignments\\img\\OIP 3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(736, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebtnActionPerformed

        dp.removeAll();
        Employe e1 = new Employe();
        dp.add(e1);
        e1.setVisible(true);
    }//GEN-LAST:event_ebtnActionPerformed

    private void dbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbtnActionPerformed
        dp.removeAll();
        Department d1 = new Department();
        dp.add(d1);
        d1.setVisible(true);
    }//GEN-LAST:event_dbtnActionPerformed

    private void ddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddbtnActionPerformed

        dp.removeAll();
        Designation dd1 = new Designation();
        dp.add(dd1);
        dd1.setVisible(true);

    }//GEN-LAST:event_ddbtnActionPerformed

    private void ubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubtnActionPerformed

        dp.removeAll();
        UserAccount u1 = new UserAccount();
        dp.add(u1);
        u1.setVisible(true);
    }//GEN-LAST:event_ubtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        welcom gb = new welcom();
        gb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebtn1ActionPerformed

        dp2.removeAll();
        a_employe e1 = new a_employe();
        dp2.add(e1);
        e1.setVisible(true);
    }//GEN-LAST:event_ebtn1ActionPerformed

    private void dbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbtn1ActionPerformed
        dp2.removeAll();
        a_department d1 = new a_department();
        dp2.add(d1);
        d1.setVisible(true);
    }//GEN-LAST:event_dbtn1ActionPerformed

    private void ddbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddbtn1ActionPerformed

        dp2.removeAll();
        a_designation dd1 = new a_designation();
        dp2.add(dd1);
        dd1.setVisible(true);

    }//GEN-LAST:event_ddbtn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        welcom gb = new welcom();
        gb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dbtn;
    private javax.swing.JButton dbtn1;
    private javax.swing.JButton ddbtn;
    private javax.swing.JButton ddbtn1;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JDesktopPane dp2;
    private javax.swing.JButton ebtn;
    private javax.swing.JButton ebtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton ubtn;
    // End of variables declaration//GEN-END:variables
}
