/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inf;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sharo
 */
public class Department extends javax.swing.JInternalFrame {

    /**
     * Creates new form Department
     */
    public Department() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        tfdipID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDepart = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdipName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        depsave = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        emsg.setForeground(new java.awt.Color(204, 0, 0));
        emsg.setText("jLabel2");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharo\\OneDrive\\Desktop\\Semester 2 assingment\\java\\OopAssignments\\img\\OIP 3.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfdipID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdipIDActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbDepart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DepartmentName", "DepartmentID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDepartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDepart);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 300));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Department  Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("DepartmentID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));
        jPanel1.add(tfdipName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 150, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton3.setText("Delete ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 90, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 90, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 90, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        depsave.setBackground(new java.awt.Color(204, 204, 204));
        depsave.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        depsave.setText("save");
        depsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depsaveActionPerformed(evt);
            }
        });
        jPanel1.add(depsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "IT", "Design", "Business Development", "Marketing", "finances " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sharo\\OneDrive\\Desktop\\Semester 2 assingment\\java\\OopAssignments\\img\\OIP 3.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDepartMouseClicked
     
         
        

    }//GEN-LAST:event_tbDepartMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

DefaultTableModel model = (DefaultTableModel) tbDepart.getModel();

if (!tfdipName.getText().trim().isEmpty() && jComboBox1.getSelectedItem() != null) {
    Object selectedItem = jComboBox1.getSelectedItem();
    model.addRow(new Object[]{selectedItem.toString(), tfdipName.getText()});
} else {
    
}

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model = (DefaultTableModel) tbDepart.getModel();
int selectedRowIndex = tbDepart.getSelectedRow();

if (selectedRowIndex != -1) { 
    Object selectedComboItem = jComboBox1.getSelectedItem();
    String updatedID = (selectedComboItem != null) ? selectedComboItem.toString() : "";

    String updatedName = tfdipName.getText().trim();

    if (!updatedID.isEmpty() && !updatedName.isEmpty()) {
        model.setValueAt(updatedID, selectedRowIndex, 0);
        model.setValueAt(updatedName, selectedRowIndex, 1);
    }
    
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                             
    DefaultTableModel model = (DefaultTableModel) tbDepart.getModel();
    int selectedRowIndex = tbDepart.getSelectedRow();

    if (selectedRowIndex != -1) { 
        model.removeRow(selectedRowIndex);
        
        tfdipID.setText("");
        tfdipName.setText("");
    
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void depsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depsaveActionPerformed
        
         DefaultTableModel model = (DefaultTableModel) tbDepart.getModel();

    StringBuilder tableContent = new StringBuilder();
    for (int i = 0; i < model.getRowCount(); i++) {
        for (int j = 0; j < model.getColumnCount(); j++) {
            tableContent.append(model.getValueAt(i, j)).append("\t");
        }
        tableContent.append("\n");
    }

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save Data to Text File");
    int userSelection = fileChooser.showSaveDialog(null);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
            writer.write(tableContent.toString());
            writer.flush();
            JOptionPane.showMessageDialog(null, "Data saved successfully!");
        } catch (IOException exception) {
            JOptionPane.showMessageDialog(null, "Error saving data: " + exception.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_depsaveActionPerformed

    private void tfdipIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdipIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdipIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depsave;
    private javax.swing.JLabel emsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDepart;
    private javax.swing.JTextField tfdipID;
    private javax.swing.JTextField tfdipName;
    // End of variables declaration//GEN-END:variables

    private void searchAndDisplayData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
